import { aqua,
  cream1,
  cream2,
  cream3,
  cleanser3,
  cleanser5,
  essence2,
  essence3,
  gel1,
  lotion,
  moisture1,
  serum,
  serum3,
  serum4,
  toner,
  toner3,
  toner6,
  toner7,
  anua,
  anua1,
  anua2,
  anuaserum,
  anuacleanser,
  anuacleanser1,
  anuatoner,
  anuacream,
  anuacream1,
  anuaserum1,
  anuatoner1,
  anuatoner2,
  anuaserum2,
  anuaserum3,
  anuaserum4,
  anuasoothing,
  ceravecleanser,
  ceravebodywash,
  ceravecream,
  ceravecleanser1,
  ceravecleanser2,
  ceravecleanser3,
  ceravecleanser4,
  ceravebodywash1,
  ceravebodywash2,
  ceravebodywash3,
  ceravebodywash4,
  ceravelotion,
  gmserum,
  gmserum1,
  gmserum2,
  gmserum3,
  gmlotion,
  gmtoner,
  gmtoner1,
  gmexfoliation,
  gmpowder,
  numcleanser,
  numcream,
  numcream1,
  numcream2,
  numcream3,
  numcream4,
  numserum,
  numserum1,
  numserum2,
  numserum3,
  numserum4,
  numserum5,
  numserum6,
  numserum7,
  numsunscreen,
  numsunscreen1,
  numsunscreen2,
  numtoner,
  numtoner1,
  numtoner2,
  olaybodywash,
  olaybodywash1,
  olaybodywash2,
  olaybodywash3,
  olaybodywash4,
  olaylotion,
  olaylotion1,
  olaylotion2,
  olaylotion3,
  olaylotion4,
  team1, } from "../assets";

export const links = [
  { name: "Shop", link: "/shop" },
  { name: "About", link: "/about" },
  { name: "Blog", link: "/blog" },
  { name: "Contact us", link: "/contact" },
  // { id: "4", name: "UpdateProfile", url: "update-profile"},
];
export const features = [
  { 
    _id: "11", 
    name: "ACWELL phyto active balancing cream", 
    image: cream2, 
    price: "30.00",
    text: "Bestsellers",
  },
  { 
    _id: "4", 
    name: "ACWELL on bija essence", 
    image: essence2, 
    price: "30.00", 
    text: "Bestsellers"
  },
  { 
    _id: "14", 
    name: "ACWELL a.Cureal-9 control X gel", 
    image: gel1, 
    price: "25.00",
    text: "Bestsellers", 
  },
];

export const newArrivals = [
  { 
    _id: "15", 
    name: "niacinamide 10%+TXA 4% dar spot correcting serum", 
    image: anuaserum, 
    price: "30.00",
  },
  { 
    _id: "17", 
    name: "BHA 2% gentle exfoliating toner", 
    image: anuatoner, 
    price: "30.00",
  },
  { 
    _id: "16", 
    name: "heartleaf pore control cleansing oil", 
    image: anuacleanser, 
    price: "30.00",
  },
];

export const testimonials = [
  {
    id : "0",
    text : "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati. Explicabo nobis labore adipisci! Aspernatur, esse provident. Facere quia deserunt odit architecto eos quas aperiam et.",
    name : "Sophia",
  },
  {
    id : "1",
    text : "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati. Explicabo nobis labore adipisci! Aspernatur, esse provident. Facere quia deserunt odit architecto eos quas aperiam et.",
    name : "Bennett",
  },
  {
    id : "2",
    text : "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati. Explicabo nobis labore adipisci! Aspernatur, esse provident. Facere quia deserunt odit architecto eos quas aperiam et.",
    name : "Liam",
  },
  {
    id : "3",
    text : "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati. Explicabo nobis labore adipisci! Aspernatur, esse provident. Facere quia deserunt odit architecto eos quas aperiam et.",
    name : "Turner",
  },
  {
    id : "4",
    text : "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati. Explicabo nobis labore adipisci! Aspernatur, esse provident. Facere quia deserunt odit architecto eos quas aperiam et.",
    name : "Ava",
  },
];


export const products = [
  { 
    _id: "0", 
    name: "ACWELL real aqua balancing lotion ", 
    image: "/image/acwell/balancing-lotion.jpg", 
    category: "acwell", 
    price: "28.00",
    size: "150ml",
  },
  { 
    _id: "1", 
    name: "ACWELL real aqua balancing toner", 
    image: "/image/acwell/balancing_toner.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "150ml",
  },
  { 
    _id: "2", 
    name: "ACWELL real aqua balancing cream", 
    image: "/image/acwell/balancing-cream1.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "3", 
    name: "ACWELL real aqua balancing ampoule", 
    image: "/image/acwell/balancing-serum.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "4", 
    name: "ACWELL ON bija essence", 
    image: "/image/acwell/onbija1.webp", 
    category: "acwell", 
    price: "30.00",
    size: "150ml",
  },
  { 
    _id: "5", 
    name: "ACWELL licorice ph balancing advance serum", 
    image: "/image/acwell/brighten-serum.jpg", 
    category: "acwell", 
    price: "28.00",
    size: "30ml",
  },
  { 
    _id: "6", 
    name: "ACWELL licorice ph balancing cleansing toner", 
    image: "/image/acwell/brighten-toner.jpg", 
    category: "acwell", 
    price: "20.00",
    size: "50ml",
  },
  { 
    _id: "7", 
    name: "ACWELL licorice ph balancing intensive eye cream", 
    image: "/image/acwell/ph_eye-cream.jpg", 
    category: "acwell", 
    price: "35.00",
    size: "60ml",
  },
  { 
    _id: "8", 
    name: "ACWELL licorice ph balancing extreme moisture", 
    image:"/image/acwell/ph-moisture1.jpg", 
    category: "acwell", 
    price: "25.00",
    size: "60ml",
  },
  { 
    _id: "9", 
    name: "ACWELL phyto active balancing ampoule", 
    image: "/image/acwell/dryness-serum.jpg", 
    category: "acwell", 
    price: "35.00",
    size: "50ml",
  },
  { 
    _id: "10", 
    name: "ACWELL phyto active balancing toner", 
    image: "/image/acwell/dryness-toner1.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "150ml",
  },
  { 
    _id: "11", 
    name: "ACWELL phyto active balancing cream", 
    image: "/image/acwell/dryness-toner.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "12", 
    name: "ACWELL pH balancing bubble free cleansing gel", 
    image: "/image/acwell/ph_cleansing2.webp", 
    category: "acwell", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "13", 
    name: "ACWELL licorice pH balancing pore cleansing gel", 
    image: "/image/acwell/pore-cleansing.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "14", 
    name: "ACWELL a.Cureal-9 control X gel", 
    image: "/image/acwell/x-gel4-1.jpg", 
    category: "acwell", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "15", 
    name: "ANUA niacinamide 10%+TXA 4% dack spot correcting serum", 
    image: "/image/anua/anua-ampouleserum-niacinamide.webp", 
    category: "anua", 
    price: "22.00",
    size: "30ml",
  },
  { 
    _id: "16", 
    name: "ANUA heartleaf pore control cleansing oil", 
    image: "/image/anua/anua-cleanser.webp", 
    category: "anua", 
    price: "25.00",
    size: "200ml",
  },
  { 
    _id: "17", 
    name: "ANUA BHA 2% gentle exfoliating toner", 
    image: "/image/anua/anua-exfoliatingtoner.webp", 
    category: "anua", 
    price: "30.00",
    size: "150ml",
  },
  { 
    _id: "18", 
    name: "ANUA heartleaf quercetinol pore deep cleansing foam", 
    image: "/image/anua/anua-cleanserheartleaf.webp", 
    category: "anua", 
    price: "18.00",
    size: "200ml",
  },
  { 
    _id: "19", 
    name: "ANUA heartleaf 70% intense calming cream", 
    image: "/image/anua/anua-moisturizer.webp", 
    category: "anua", 
    price: "38.00",
    size: "50ml",
  },
  { 
    _id: "20", 
    name: "ANUA peach 70% niacinamide serum", 
    image: "/image/anua/anua-serum.webp", 
    category: "anua", 
    price: "30.00",
    size: "30ml",
  },
  { 
    _id: "21", 
    name: "ANUA heartleaf 77% soothing toner", 
    image: "/image/anua/anua-toner.webp", 
    category: "anua", 
    price: "28.00",
    size: "250ml",
  },
  { 
    _id: "22", 
    name: "ANUA heartleaf 77% toner pad", 
    image: "/image/anua/anua-tonerpad.webp", 
    category: "anua", 
    price: "30.00",
    size: "160ml",
  },
  { 
    _id: "23", 
    name: "ANUA green lemon vitamin c blemish serum", 
    image: "/image/anua/anuaserum.webp", 
    category: "anua", 
    price: "48.00",
    size: "20ml",
  },
  { 
    _id: "24", 
    name: "ANUA hearrleaf 80% moisture soothing ampoule", 
    image: "/image/anua/anuasoothing-ampoule.webp", 
    category: "anua", 
    price: "35.00",
    size: "30ml",
  },
  { 
    _id: "25", 
    name: "ANUA phyto active balancing cream", 
    image: "/image/anua/anua-ampule.webp", 
    category: "anua", 
    price: "30.00",
    size: "200ml",
  },
  { 
    _id: "25", 
    name: "ANUA heartleaf 70% daily lotion", 
    image: "/image/anua/anua-moisturizer1.webp", 
    category: "anua", 
    price: "28.00",
    size: "200ml",
  },
  { 
    _id: "26", 
    name: "CERAVE acne control cleanser", 
    image:  "/image/cerave/acne-controlcleanser.webp",
    category: "cerave", 
    price: "18.00",
    size: "237ml",
  },
  { 
    _id: "27", 
    name: "CERAVE foaming facial cleanser", 
    image: "/image/cerave/cerave_foamingcleanser.webp", 
    category: "cerave", 
    price: "15.48",
    size: "355ml",
  },
  { 
    _id: "28", 
    name: "CERAVE hydrating facial cleanser", 
    image: "/image/cerave/cerave_hydratingcleanser.webp", 
    category: "cerave", 
    price: "15.48",
    size: "355ml",
  },
  { 
    _id: "29", 
    name: "CERAVE hydrating cream-to-foam cleanser", 
    image: "/image/cerave/cream-foamcleanser.webp", 
    category: "cerave", 
    price: "16.00",
    size: "355ml",
  },
  { 
    _id: "30", 
    name: "CERAVE hydrating foaming oil cleanser", 
    image: "/image/cerave/hydrating_oilcleanser.webp", 
    category: "cerave", 
    price: "20.00",
    size: "237ml",
  },
  { 
    _id: "31", 
    name: "CERAVE SA body wash for rough & bumpy skin", 
    image: "/image/cerave/cerave_bodywash.webp",
    category: "cerave", 
    price: "16.00",
    size: "296ml",
  },
  { 
    _id: "32", 
    name: "CERAVE diabetic cleansing wash", 
    image: "/image/cerave/diabetics-cleansingWash.jpg", 
    category: "cerave", 
    price: "18.00",
    size: "296ml"
  },
  { 
    _id: "33", 
    name: "CERAVE hydrating body wash", 
    image: "/image/cerave/hydrating_bodywash.webp", 
    category: "cerave", 
    price: "15.00",
    size: "296ml"
  },
  { 
    _id: "34", 
    name: "CERAVE renewing SA cleanser", 
    image: "/image/cerave/renewing_cleanser.webp", 
    category: "cerave", 
    price: "14.00",
    size: "237ml",
  },
  { 
    _id: "35", 
    name: "CERAVE soothing body wash", 
    image: "/image/cerave/soothing-bodywash.webp", 
    category: "cerave", 
    price: "18.00",
    size: "296ml"
  },
  { 
    _id: "36", 
    name: "CERAVE moisturizing cream", 
    image: "/image/cerave/cerave_cream.webp", 
    category: "cerave", 
    price: "17.00",
    size: "16.OZ",
  },
  { 
    _id: "37", 
    name: "CERAVE SA lotion for rough & bumpy skin", 
    image: "/image/cerave/roughbumpy-skin.webp", 
    category: "cerave", 
    price: "18.00",
    size: "237ml",
  },
  { 
    _id: "38", 
    name: "GOOD MOLECULES daily brightening serum", 
    image: "/image/good-molecules/daily_brightening_serum.webp",
    category: "good molecules", 
    price: "12.00",
    size: "30ml",
  },
  { 
    _id: "39", 
    name: "GOOD MOLECULES discoloration correcting serum", 
    image: "/image/good-molecules/dcs_serum.webp", 
    category: "good molecules", 
    price: "30.00",
    size:  "75ml"
  },
  { 
    _id: "40", 
    name: "GOOD MOLECULES hyaluronic Aacid serum", 
    image: "/image/good-molecules/hyaluronic_serum.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "75ml"
  },
  { 
    _id: "41", 
    name: "GOOD MOLECULES niacinimide serum", 
    image: "/image/good-molecules/niacinimide_serum.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "75ml"
  },
  { 
    _id: "42", 
    name: "GOOD MOLECULES overnight exfoliating treatment", 
    image: "/image/good-molecules/overnight_exfoliating.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "30ml",
  },
  { 
    _id: "43", 
    name: "GOOD MOLECULES discoloration correcting body treatment", 
    image: "/image/good-molecules/dcbt_white.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "120ml",
  },
  { 
    _id: "44", 
    name: "GOOD MOLECULES pineapple exfoliating powder", 
    image: "/image/good-molecules/pineapple_powder.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "2.1OZ",
  },
  { 
    _id: "45", 
    name: "GOOD MOLECULES glycolic exfoliating toner", 
    image: "/image/good-molecules/glycolic_toner.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "120ml",
  },
  { 
    _id: "46", 
    name: "GOOD MOLECULES niacinimide brightening toner", 
    image: "/image/good-molecules/niacinimide_toner.webp", 
    category: "good molecules", 
    price: "30.00",
    size: "120ml"
  },
  { 
    _id: "47", 
    name: "NUMBUZIN no.1 easy peasy cleansing oil", 
    image: "/image/numbuzin/numbuzin-cleanser.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "200ml",
  },
  { 
    _id: "48", 
    name: "NUMBUZIN no.1 purple complex moisture balancing soothing cream", 
    image: "/image/numbuzin/numbuzin-cream1.jpg",
    category: "numbuzin", 
    price: "30.00",
    size: "100ml",
  },
  { 
    _id: "49", 
    name: "NUMBUZIN no.2 cica ceramide repair cream", 
    image: "/image/numbuzin/numbuzin-cream2.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "50", 
    name: "NUMBUZIN no.3 velvet beauty cream", 
    image: "/image/numbuzin/numbuzin-cream3.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "51", 
    name: "NUMBUZIN no.4 full-nutrient firming cream", 
    image: "/image/numbuzin/numbuzin-cream4.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "52", 
    name: "NUMBUZIN no.5 daily multi-Vitamin cream", 
    image: "/image/numbuzin/numbuzin-cream5.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "60ml",
  },
  { 
    _id: "53", 
    name: "NUMBUZIN no.1 glossy essence serum", 
    image: "/image/numbuzin/numbuzin1.jpg",
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "54", 
    name: "NUMBUZIN no.2 protein 43% creamy serum", 
    image: "/image/numbuzin/numbuzin2.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "55", 
    name: "NUMBUZIN no.3 skin softening serum", 
    image: "/image/numbuzin/numbuzin3.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "56", 
    name: "NUMBUZIN no.4 collagen 73% pudding serum", 
    image: "/image/numbuzin/numbuzin4.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "57", 
    name: "NUMBUZIN no.5 goodbye blemish serum", 
    image: "/image/numbuzin/numbuzin5.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "58", 
    name: "NUMBUZIN no.6 deep sleep mask serum", 
    image: "/image/numbuzin/numbuzin6.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "59", 
    name: "NUMBUZIN no.7 mild green soothing serum", 
    image: "/image/numbuzin/numbuzin7.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "60", 
    name: "NUMBUZIN no.8 fine cica serum", 
    image: "/image/numbuzin/numbuzin8.jpg", 
    category: "numbuzin", 
    price: "30.00",
    size: "50ml",
  },
  { 
    _id: "61", 
    name: "NUMBUZIN no.1 pure glass clean tone up", 
    image: "/image/numbuzin/numbuzin-sunscree1.png",
    category: "numbuzin", 
    price: "25.00",
    size: "50ml",
  },
  { 
    _id: "62", 
    name: "NUMBUZIN no.2 goodbye redness derma tone up", 
    image: "/image/numbuzin/numbuzin-sunscren2.jpg", 
    category: "numbuzin", 
    price: "25.00",
    size: "50ml",
  },
  { 
    _id: "63", 
    name: "NUMBUZIN no.3 porcelain base-skip tone up beige", 
    image: "/image/numbuzin/numbuzin-sunscreen3.jpg", 
    category: "numbuzin", 
    price: "25.00",
    size: "50ml",
  },
  { 
    _id: "64", 
    name: "NUMBUZIN no.1 goodbye dead cell toner", 
    image: "/image/numbuzin/numbuzin-toner1.jpg",
    category: "numbuzin", 
    price: "28.00",
    size: "200ml",
  },
  { 
    _id: "65", 
    name: "NUMBUZIN no.2 thermal water 89% mineral toner", 
    image: "/image/numbuzin/numbuzin-toner2.jpg", 
    category: "numbuzin", 
    price: "28.00",
    size: "200ml",
  },
  { 
    _id: "66", 
    name: "NUMBUZIN no.3 super glowing essence toner", 
    image: "/image/numbuzin/numbuzin-toner3.jpg", 
    category: "numbuzin", 
    price: "28.00",
    size: "200ml",
  },
  { 
    _id: "67", 
    name: "OLAY cleansing & nourishing body wash", 
    image: "/image/olay/olay-bodywash.jpg",
    category: "olay", 
    price: "10.00",
    size: "591ml"
  },
  { 
    _id: "68", 
    name: "OLAY cleansing & brightening body wash", 
    image: "/image/olay/olay-bodywash1.jpg", 
    category: "olay", 
    price: "10.00",
    size: "591ml"
  },
  { 
    _id: "69", 
    name: "OLAY cleansing & renewing body wash", 
    image: "/image/olay/olay-bodywash2.jpg", 
    category: "olay", 
    price: "10.00",
    size: "591ml"
  },
  { 
    _id: "70", 
    name: "OLAY age defying body wash", 
    image: "/image/olay/olay-bodywash3.jpg", 
    category: "olay", 
    price: "10.00",
    size: "591ml"
  },
  { 
    _id: "71", 
    name: "OLAY cleansing & firming body wash", 
    image: "/image/olay/olay-bodywash4.jpg", 
    category: "olay", 
    price: "10.00",
    size: "591ml"
  },
  { 
    _id: "72", 
    name: "OLAY revitalizing & hydrating body lotion", 
    image: "/image/olay/olay-lotion.jpg",
    category: "olay", 
    price: "12.00",
    size: "502ml"
  },
  { 
    _id: "73", 
    name: "OLAY tone evening & hydrating body lotion", 
    image: "/image/olay/olay-lotion1.jpg", 
    category: "olay", 
    price: "12.00",
    size: "502ml"
  },
  { 
    _id: "74", 
    name: "OLAY regenerist hand & body lotion pump", 
    image: "/image/olay/olay-lotion2.jpg", 
    category: "olay", 
    price: "12.00",
    size: "502ml"
  },
  { 
    _id: "75", 
    name: "OLAY nourishing & hydrating body lotion", 
    image: "/image/olay/olay-lotion3.jpg", 
    category: "olay", 
    price: "12.00",
    size: "502ml"
  },
  { 
    _id: "76", 
    name: "OLAY firming & hydrating body lotion", 
    image: "/image/olay/olay-lotion4.jpg", 
    category: "olay", 
    price: "12.00",
    size: "502ml"
  }
];

export const companies = [
  {name: "acwell"},
  {name: "anua"},
  {name: "cerave"},
  {name: "good molecules"},
  {name: "numbuzin"},
  {name: "olay"},
];

export const Blogs = [
  {
    id: "0",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
  },
  {
    id: "1",
    imageUrl: anua1,
    date: "January 22, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
  },
  {
    id: "2",
    imageUrl: anuaserum4,
    date: "January 22, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
  },
];

export const journal = [
  {
    id: "0",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "protect",
  },
  {
    id: "1",
    imageUrl: anua1,
    date: "January 22, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "protect",
  },
  {
    id: "2",
    imageUrl: anuaserum4,
    date: "January 22, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "protect",
  },
  {
    id: "3",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "protect",
  },
  {
    id: "4",
    imageUrl: anua1,
    date: "January 22, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "protect",
  },
  {
    id: "5",
    imageUrl: anuaserum4,
    date: "January 22, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "protect",
  },
  {
    id: "6",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "regenerates",
  },
  {
    id: "7",
    imageUrl: anua1,
    date: "January 21, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "regenerates",
  },
  {
    id: "8",
    imageUrl: anuaserum4,
    date: "January 24, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "regenerates",
  },
  {
    id: "9",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "regenerates",
  },
  {
    id: "10",
    imageUrl: anua1,
    date: "January 23, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "regenerates",
  },
  {
    id: "11",
    imageUrl: anuaserum4,
    date: "January 25, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "regenerates",
  },
  {
    id: "12",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "revitalizes",
  },
  {
    id: "13",
    imageUrl: anua1,
    date: "January 21, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "revitalizes",
  },
  {
    id: "14",
    imageUrl: anuaserum4,
    date: "January 24, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "revitalizes",
  },
  {
    id: "15",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "revitalizes",
  },
  {
    id: "16",
    imageUrl: anua1,
    date: "January 23, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "revitalizes",
  },
  {
    id: "17",
    imageUrl: anuaserum4,
    date: "January 25, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "revitalizes",
  },
  {
    id: "18",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "strengthens",
  },
  {
    id: "19",
    imageUrl: anua1,
    date: "January 21, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "strengthens",
  },
  {
    id: "20",
    imageUrl: anuaserum4,
    date: "January 24, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "strengthens",
  },
  {
    id: "21",
    imageUrl: anua,
    date: "January 22, 2024",
    name: "NON-GREASY TEXTURE",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "strengthens",
  },
  {
    id: "22",
    imageUrl: anua1,
    date: "January 23, 2024",
    name: "SOFT, HYDRATING FINISH",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "strengthens",
  },
  {
    id: "23",
    imageUrl: anuaserum4,
    date: "January 25, 2024",
    name: "HYDRATES SKIN FOR A LONG TIME",
    text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quis, tenetur? Est placeat incidunt obcaecati.",
    category: "strengthens",
  },
];

export const Abouts =[
  {
    title: "acwell",
    product: [
      {
        _id: "",
        name: "ACWELL phyto active balancing cream", 
        image: "/image/acwell/dryness-toner.jpg", 
        price: "30.00",
      },
      {
        _id: "",
        name: "ACWELL on bija essence", 
        image: "/image/acwell/bija-essence2.webp", 
        price: "30.00",
      },
      {
        _id: "",
        name: "ACWELL acne soothing gel", 
        image: "/image/acwell/x-gel4-1.jpg", 
        price: "25.00",
      },
    ],
  },
  {
    title: "anua",
    product: [
      {
        _id: "15",
        name: "ANUA niacinamide 10%+TXA 4% dar spot correcting serum", 
        image: "/image/anua/anua-ampouleserum-niacinamide.webp", 
        price: "30.00",
      },
      {
        _id: "17",
        name: "ANUA BHA 2% gentle exfoliating toner", 
        image: "/image/anua/anua-exfoliatingtoner.webp", 
        price: "30.00",
      },
      {
        _id: "16",
        name: "ANUA heartleaf pore control cleansing oil", 
        image: "/image/anua/anua-cleanser.webp", 
        price: "30.00",
      },
    ],
  },
  {
    title: "cerave",
    product: [
      {
        _id: "28",
        name: "CERAVE hydrating facial cleanser",
        image: "/image/cerave/cerave_hydratingcleanser.webp",
        price: "15:48",
      },
      {
        _id: "34",
        name: "CERAVE renewing SA cleanser",
        image: "/image/cerave/renewing_cleanser.webp",
        price: "14:00",
      },
      {
        _id: "37",
        name: "CERAVE SA lotion for rough & bumpy skin",
        image: "/image/cerave/roughbumpy-skin.webp",
        price: "18.00",
      },
    ],
  },
  {
    title: "good molecules",
    product: [
      {
        _id: "39",
        name: "discoloration correcting serum",
        image: "/image/good-molecules/dcs_serum.webp",
        price: "32.00",
      },
      {
        _id: "46",
        name: "niacinimide brightening toner",
        image: "/image/good-molecules/niacinimide_toner.webp",
        price: "17.00",
      },
      {
        _id: "44",
        name: "pineapple exfoliating powder",
        image: "/image/good-molecules/pineapple_powder.webp",
        price: "18.00",
      },
    ],
  },
  {
    title: "numbuzin",
    product: [
      {
        _id: "57",
        name: "no.5 goodbye blemish serum",
        image: "/image/numbuzin/numbuzin5.jpg",
        price: "29.50",
      },
      {
        _id: "51",
        name: "no.4 full-nutrient firming cream",
        image: "/image/numbuzin/numbuzin-cream4.jpg",
        price: "31.30",
      },
      {
        _id: "65",
        name: "no.2 thermal water 89% mineral toner",
        image: "/image/numbuzin/numbuzin-toner2.jpg",
        price: "25.00",
      },
    ],
  },
  {
    title: "olay",
    product: [
      {
        _id: "75",
        name: "OLAY nourishing & hydrating body lotion",
        image: "/image/olay/olay-lotion3.jpg",
        price: "12.00",
      },
      {
        _id: "73",
        name: "OLAY tone evening & hydrating body lotion",
        image: "/image/olay/olay-lotion1.jpg",
        price: "12.00",
      },
      {
        _id: "69",
        name: "OLAY cleansing & renewing body wash",
        image: "/image/olay/olay-bodywash2.jpg",
        price: "12.50",
      },
    ],
  },
];

export const ourTeam =[
  {
    id: "0",
    imageUrl: team1,
    name: "elena ada",
    title: "CEO & founder",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
  {
    id: "1",
    imageUrl: team1,
    name: "sophia bennett",
    title: "chief scientist",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
  {
    id: "2",
    imageUrl: team1,
    name: "ella nina",
    title: "sales & partnerships manager",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
  {
    id: "3",
    imageUrl: team1,
    name: "lucas savannah",
    title: "quality assurance specialist",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
  {
    id: "4",
    imageUrl: team1,
    name: "oliver mitchell",
    title: "customer care manager",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
  {
    id: "5",
    imageUrl: team1,
    name: "eliam morgan",
    title: "marketing director",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
  {
    id: "6",
    imageUrl: team1,
    name: "ava turner",
    title: "creative director",
    desc:  " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia impedit laudantium dolorem asperiores, dignissimos optio. Quod possimus voluptatum corrupti nesciunt eligendi officiis veritatis porro modi ex.",
  },
];

export const images =[ 
  gel1, lotion, aqua, cream3,
];


